apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pet-clinic-dev
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/jeffellin/spring-petclinic-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
