apiVersion: v1
kind: Secret
metadata:
  name: "svn-rms"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "SVN credentials for getting to heritage RMS codebases"
type: Opaque
stringData:
  username: corprmssvn
  password: 'XXXXXXXXXX'
